export const SAVE_COMPETITIONS = 'SAVE_COMPETITIONS';
export const SAVE_STANDINGS = 'SAVE_STANDINGS';
export const SAVE_TEAM = 'SAVE_TEAM';
export const SAVE_MATCHES = 'SAVE_MATCHES';
export const SAVE_TEAM_MATCHES = 'SAVE_TEAM_MATCHES';
export const SAVE_SCORERS_DATA = 'SAVE_SCORERS_DATA';
export const CHANGE_CURRENT_TABLE = 'CHANGE_CURRENT_TABLE';
export const FILTER_MATCHES = 'FILTER_MATCHES';